openapi: 3.0.0
info:
    title: KAIST board of audit and inspection system API
    version: 1.0.0
# servers:
# - url: http://api.example.com/v1
# description: Optional server description, e.g. Main (production) server
tags:
    - name: 피감기구
      description: 피감기구 관련 API
    - name: 예산안
      description: 예산안 관련 API



paths:
    /organizations:
        get:
            description: 모든 피감기구 조회
            tags: [피감기구]
            responses:
                '200': # status code
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Organization'
        post:
            description: 피감기구 생성
            tags: [피감기구]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: 피감기구 이름
                                    example: 학부총학생회
            responses:
                '200': # status code
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Organization'
        delete:
            description: 피감기구 삭제
            tags: [피감기구]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: 피감기구 이름
                                    example: 학부총학생회
            responses:
                '200': # status code
                    description: OK
    
    /budget:
        get:
            summary: 모든 예산안 조회
            description: 데이터베이스로부터 주어진 검색 옵션에 맞는 모든 예산안의 array를 가져 옴.
            tags: [예산안]
            responses:
                    200:
                        description: Successfully retrieved budgets
                        content:
                            application/json:
                                schema:
                                    type: array
                                    items: Budget
                                    $ref: '#/components/schemas/Budget'
                    500:
                        description: Server error or database error
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        message:
                                            type: string

    /budget/expense/{budget_id}:
        get:
            summary: 지출 예산안 조회
            description: 지출 예산안 id에 해당하는 지출안의 array를 가져 옴.
            tags: [예산안]
        
            parameters:
                - name: budget_id
                  in: path
                  description: 지출 예산안 id
                  required: true
                  schema:
                    type: integer
                    format: int32
                    example: 1
                  
            responses:
                '200': # status code
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Expense'
                '500': # status code
                    description: Server error or database error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                

                                
        post:
            summary: 지출 예산안 등록
            description: 지출 예산안 id에 해당하는 예산안을 등록함.
            tags: [예산안]

            parameters:
                - name: budget_id
                  in: path
                  description: 지출 예산안 id
                  required: true
                  schema:
                    type: integer
                    format: int32
                    example: 1
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Expense'
            responses:
                200:
                    description: Created expense
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Expense'

        delete:
            summary: 지출 예산안 삭제
            description: 지출 예산안 id에 해당하는 지출안을 삭제함.
            tags: [예산안]
            parameters:
                - name: budget_id
                  in: path
                  description: 지출 예산안 id
                  required: true
                  schema:
                    type: integer
                    format: int32
                    example: 1
                  
            responses:
                '200': # status code
                    description: OK
                '500': # status code
                    description: Server error or database error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                

        put:
            summary: 지출 예산안 업데이트
            description: 지출 예산안 id에 해당하는 예산안을 입력하는 지출 예산안 값으로 업데이트함.
            tags: [예산안]
            parameters:
                - name: budget_id
                  in: path
                  description: 지출 예산안 id
                  required: true
                  schema:
                    type: integer
                    format: int32
                    example: 1
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Expense'
            responses:
                200:
                    description: Successfuly updated expense
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Expense'
                500:
                    description: Server error or database error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string

    /budget/report/expense/{organization_id}/{year}/{half}:
        get:
    

    /budget/{organization_id}/{year}{half}:
        post:
    






components:
    schemas:
        Organization:
            type: object
            properties:
                id:
                    type: integer
                    description: 피감기구 id
                    example: 1
                name:
                    type: string
                    description: 피감기구 이름
                    example: 학부총학생회
                created_at:
                    type: timestampe
                    example: 2020-01-01 00:00:00
                updated_at:
                    type: string
                    example: 2020-01-01 00:00:00
        Expense:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                    description: A unique identifier for each expense entry.
                source:
                    type: string
                    enum:
                        - 학생회비
                        - 본회계
                        - 자치
                    description: 지출 예산안 재원
                category:
                    type: string
                    description: 예산 분류
                project:
                    type: string
                    description: 사업명
                content:
                    type: string
                    description: 항목 (세부 항목)
                amount:
                    type: integer
                    format: int32
                    description: 금액
                note:
                    type: string
                    description: 비고
            required:
                - id
                - source
                - category
                - project
                - content
                - amount

        Budget:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                    description: A unique identifier for each budget entry. Automatically incremented.
                manager:
                    type: string
                    description: 담당자
                year:
                    type: integer
                    format: int32
                    description: 집행연도
                half:
                    type: string
                    enum:
                        - spring
                        - fall
                    description: 예산 집행 반기 (spring, fall)
            required:
                - id
                - manager
                - year
                - half